// Blog content layer for the reinstated Amy Tangerine blog (t812).
//
// Source: content/blog/*, generated by scripts/blog-migration/extract.py from the
// captured Squarespace legacy HTML archive. The shell reads the parsed JSON; the
// t811 migration pipeline later formalizes MDX + re-hosted images on the same data.
//
// All reads are build-time (the JSON ships in the repo), so these are sync fs reads
// behind React's `cache` -- no runtime cost, regenerated whenever the JSON changes.

import { cache } from "react"
import fs from "node:fs"
import path from "node:path"

const CONTENT_DIR = path.join(process.cwd(), "content", "blog")
const POSTS_DIR = path.join(CONTENT_DIR, "posts")

// Default-feed window: posts on/after this date show on the /blog index by default
// (per the PRD curation model -- recent voice up front, long tail in the archive).
export const DEFAULT_FEED_SINCE = "2019-01-01"
export const POSTS_PER_PAGE = 12

export type PostMeta = {
  slug: string
  title: string
  date: string | null
  datePublishedISO: string | null
  tags: string[]
  excerpt: string
  legacyPath: string
  legacyFile: string
  imageCount: number
}

export type Post = PostMeta & { body: string }

export const getAllPostsMeta = cache((): PostMeta[] => {
  const file = path.join(CONTENT_DIR, "_posts.json")
  if (!fs.existsSync(file)) return []
  const posts = JSON.parse(fs.readFileSync(file, "utf-8")) as PostMeta[]
  // Already sorted desc by the extractor; re-sort defensively.
  return posts.sort((a, b) => (b.date ?? "").localeCompare(a.date ?? ""))
})

export const getPostBySlug = cache((slug: string): Post | null => {
  const file = path.join(POSTS_DIR, `${slug}.json`)
  if (!fs.existsSync(file)) return null
  return JSON.parse(fs.readFileSync(file, "utf-8")) as Post
})

// Recent default feed: the front door. Last ~5 years of voice, not the 1,300-post wall.
export function getDefaultFeed(): PostMeta[] {
  return getAllPostsMeta().filter((p) => (p.date ?? "") >= DEFAULT_FEED_SINCE)
}

export function getYears(): string[] {
  const years = new Set<string>()
  for (const p of getAllPostsMeta()) {
    if (p.date) years.add(p.date.slice(0, 4))
  }
  return [...years].sort((a, b) => b.localeCompare(a))
}

export function getPostsByYear(year: string): PostMeta[] {
  return getAllPostsMeta().filter((p) => (p.date ?? "").startsWith(year))
}

export type TagCount = { tag: string; slug: string; count: number }

export const getTags = cache((): TagCount[] => {
  const counts = new Map<string, number>()
  for (const p of getAllPostsMeta()) {
    for (const t of p.tags) counts.set(t, (counts.get(t) ?? 0) + 1)
  }
  return [...counts.entries()]
    .map(([tag, count]) => ({ tag, slug: tagToSlug(tag), count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag))
})

export function tagToSlug(tag: string): string {
  return tag
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

export function getPostsByTag(tagSlug: string): { tag: string; posts: PostMeta[] } {
  // Normalize the incoming param so both the canonical slug ("behind-the-scenes")
  // AND a legacy SQS category form ("Behind the Scenes", "Behind+the+Scenes" once
  // URL-decoded) resolve to the same tag. This lets /blog/category/* redirects land
  // without a per-tag rewrite map.
  const want = tagToSlug(decodeURIComponent(tagSlug))
  const posts = getAllPostsMeta().filter((p) =>
    p.tags.some((t) => tagToSlug(t) === want)
  )
  const tag = posts[0]?.tags.find((t) => tagToSlug(t) === want) ?? tagSlug
  return { tag, posts }
}

// Featured / merchandised tiles at the top of the Journal (Amy's curated picks).
// content/blog/_featured.json is an array of { slug, label?, blurb?, cover? }.
// cover defaults to the post's first body image when omitted. Hidden when absent.
export type FeaturedPost = PostMeta & {
  label?: string
  blurb?: string
  cover?: string
}

function firstBodyImage(slug: string): string | undefined {
  const post = getPostBySlug(slug)
  if (!post) return undefined
  const m = post.body.match(/<img[^>]+src="([^"]+)"/)
  return m?.[1]
}

export const getFeatured = cache((): FeaturedPost[] => {
  const file = path.join(CONTENT_DIR, "_featured.json")
  if (!fs.existsSync(file)) return []
  const entries = JSON.parse(fs.readFileSync(file, "utf-8")) as Array<{
    slug: string
    label?: string
    blurb?: string
    cover?: string
  }>
  const bySlug = new Map(getAllPostsMeta().map((p) => [p.slug, p]))
  return entries
    .map((e) => {
      const meta = bySlug.get(e.slug)
      if (!meta) return null
      return {
        ...meta,
        label: e.label,
        blurb: e.blurb,
        cover: e.cover ?? firstBodyImage(e.slug),
      }
    })
    .filter((p): p is FeaturedPost => Boolean(p))
})

// "Start here" pin set (t814 will finalize Amy's picks from a candidate shortlist).
// Until then this reads an optional content/blog/_start-here.json (array of slugs);
// absent -> module hides gracefully, no hand-curation required for the shell to ship.
export const getStartHere = cache((): PostMeta[] => {
  const file = path.join(CONTENT_DIR, "_start-here.json")
  if (!fs.existsSync(file)) return []
  const slugs = JSON.parse(fs.readFileSync(file, "utf-8")) as string[]
  const bySlug = new Map(getAllPostsMeta().map((p) => [p.slug, p]))
  return slugs.map((s) => bySlug.get(s)).filter((p): p is PostMeta => Boolean(p))
})

// Posts on/before this date show the "From the archive" notice. The blog went
// dark ~2021; the live cadence resumes 2026. Anything before ARCHIVAL_BEFORE reads
// as historical. Tune as the new-post cadence builds a recent body of work.
export const ARCHIVAL_BEFORE = "2024-01-01"

export function isArchivalPost(date: string | null): boolean {
  if (!date) return true // undated legacy posts are archival by definition
  return date < ARCHIVAL_BEFORE
}

export function formatDate(date: string | null): string {
  if (!date) return ""
  const d = new Date(date + "T12:00:00Z")
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  })
}
