#!/usr/bin/env python3
"""
Generate lib/blog-redirects.ts (the legacy->clean-slug exception map) from the
extractor's content/blog/_redirects.json.

Most legacy SQS blog paths are a pure date-strip:
    /blog/YYYY/MM(/DD)?/<slug>  ->  /blog/<slug>
and are handled by ONE regex in next.config.mjs. This script emits only the
EXCEPTIONS where the clean slug differs from a pure strip:
  - opaque SQS hash ids (0m33jp7...)  -> title-derived slug
  - 'html'-suffixed slugs (dont-laughhtml) -> cleaned
  - slug collisions (two posts named motivational-monday) -> -2/-3 suffixes

Exceptions are emitted FIRST in next.config so a colliding dated path doesn't get
mis-collapsed onto the wrong post by the general rule.

Run: python3 scripts/blog-migration/gen-redirects.py
"""
import json, re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
redirects = json.loads((REPO / "content/blog/_redirects.json").read_text())

DATE_STRIP = re.compile(r"^/blog/20\d{2}/\d{1,2}(?:/\d{1,2})?/(.+)$")

exceptions = []
for legacy, target in redirects.items():
    if legacy == target:
        continue  # clean slug already; the /blog/[slug] route serves it directly
    m = DATE_STRIP.match(legacy)
    if m and target == f"/blog/{m.group(1)}":
        continue  # pure date-strip; handled by the general regex
    exceptions.append((legacy, target))

header = """// AUTO-GENERATED by scripts/blog-migration/gen-redirects.py -- do not edit by hand.
// Legacy Squarespace blog paths whose clean slug differs from a pure date-strip:
//   opaque SQS ids, 'html'-suffixed slugs, and slug collisions (-2/-3 suffixes).
// These MUST be matched before the general /blog/:y/:m/:d?/:slug -> /blog/:slug rule,
// because for a collision the dated path's clean-strip would hit the WRONG post.
export const blogLegacyRedirects = [
"""
body = "\n".join(
    f"  {{ source: {json.dumps(k)}, destination: {json.dumps(v)}, permanent: true }},"
    for k, v in exceptions
)
(REPO / "lib/blog-redirects.mjs").write_text(header + body + "\n]\n")
print(f"Wrote lib/blog-redirects.mjs with {len(exceptions)} exception redirects "
      f"(of {len(redirects)} total legacy paths).")
